# Generated by Django 3.0.6 on 2020-05-17 17:27

from django.db import migrations


def forwards(apps, schema):
    Teacher = apps.get_model('teachers', 'Teacher')

    for teacher in Teacher.objects.all().only('first_name', 'last_name').iterator():
        teacher.first_name = teacher.first_name.capitalize()
        teacher.last_name = teacher.last_name.capitalize()
        teacher.save(update_fields=['first_name', 'last_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_phone'),
    ]

    operations = [
    ]
