# Generated by Django 3.0.6 on 2020-05-17 18:50

from django.db import migrations

from group.models import Group # noqa


def forwards(apps, schema):
    Group = apps.get_model('group', 'Group') # noqa

    for group in Group.objects.all().only('first_name', 'last_name').iterator():
        group.first_name = group.first_name.capitalize()
        group.last_name = group.last_name.capitalize()
        group.save(update_fields=['first_name', 'last_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
    ]
