# Generated by Django 3.0.6 on 2020-05-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20200524_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='training_completed',
            field=models.BooleanField(null=True),
        ),
    ]
